language: node_js

node_js:
  - '8'

script: yarn run test:ci

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - codeclimate-test-reporter < ./coverage/lcov.info
